---
- name: Add apt-key of helm
  become: true
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add helm repository
  become: true
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Update repositories cache and install helm
  become: true
  apt:
    name: helm
    update_cache: yes
